#include <cstdlib>
#include <csignal>
#include <csetjmp>
#include <cstdarg>
#include <typeinfo>
#include <typeindex>
#include <type_traits>
#include <bitset>
#include <functional>
#include <utility>
#include <ctime>
#include <chrono>
#include <cstddef>
#include <initializer_list>
#include <tuple>
#include <new>
#include <memory>
#include <scoped_allocator>
#include <climits>
#include <cfloat>
#include <cstdint>
#include <cinttypes>
#include <limits>
#include <exception>
#include <stdexcept>
#include <cassert>
#include <system_error>
#include <cerrno>
#include <cctype>
#include <cwctype>
#include <cstring>
#include <cwchar>
#include <cuchar>
#include <string>
#include <array>
#include <vector>
#include <deque>
#include <list>
#include <forward_list>
#include <set>
#include <map>
#include <unordered_set>
#include <unordered_map>
#include <stack>
#include <queue>
#include <algorithm>
#include <iterator>
#include <cmath>
#include <complex>
#include <valarray>
#include <random>
#include <numeric>
#include <ratio>
#include <cfenv>
#include <iosfwd>
#include <ios>
#include <istream>
#include <ostream>
#include <iostream>
#include <fstream>
#include <sstream>
#include <strstream>
#include <iomanip>
#include <streambuf>
#include <cstdio>
#include <locale>
#include <clocale>
#include <codecvt>
#include <regex>
#include <atomic>
#include <thread>
#include <mutex>
#include <future>
#include <condition_variable>
#include <ciso646>
#include <ccomplex>
#include <ctgmath>
#include <cstdalign>
#include <cstdbool>
#include <optional>

#include <QtCore>
#include <QtNetwork>
#include <QtConcurrent>

#include <QtGui>
#include <QtQml>
#include <QtQuick>
#include <QtQuickControls2>
#include <QtSvg>
#include <QtWidgets>
#include <QtLocation>
#include <QtPositioning>

//#include <QObject>
//#include <QHostAddress>
//#include <QMetaType>
//#include <QMap>
//#include <QtConcurrent>
//#include <QCoreApplication>
//#include <QList>
//#include <QByteArray>
//#include <QObject>
//#include <QVector>
//#include <QTimer>
//#include <QDirIterator>
//#include <QThread>
//#include <QByteArray>
//#include <QString>
//#include <QDebug>
//#include <QFile>
//#include <QString>
//#include <QMap>
//#include <QDebug>
//#include <QDir>
//#include <QDebug>
//#include <QString>
//#include <QDateTime>
//#include <QByteArray>
//#include <QByteArray>
//#include <QHostAddress>
//#include <QObject>
//#include <QString>
//#include <QMutex>
//#include <QTemporaryFile>

//#include <QVariantMap>

//#include <QTimer>
//#include <QObject>
//#include <QUdpSocket>
//#include <QNetworkDatagram>
//#include <QThread>
//#include <QJsonDocument>
//#include <QJsonObject>
//#include <QNetworkAddressEntry>
//#include <QNetworkInterface>
//#include <QRandomGenerator>
